# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rrqr_rcpp <- function(X) {
    .Call('_rrqr_rrqr_rcpp', PACKAGE = 'rrqr', X)
}

rcppeigen_hello_world <- function() {
    .Call('_rrqr_rcppeigen_hello_world', PACKAGE = 'rrqr')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_rrqr_rcppeigen_outerproduct', PACKAGE = 'rrqr', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_rrqr_rcppeigen_innerproduct', PACKAGE = 'rrqr', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_rrqr_rcppeigen_bothproducts', PACKAGE = 'rrqr', x)
}

